"""
App Constants
"""

BELARUS = "Беларусь"
BGG = "bgg"
BYN = "BYN"
FIFTHELEMENT = "fifthelement"
HOBBYGAMES = "hobbygames"
KUFAR = "kufar"
LAVKAIGR = "lavkaigr"
NOT_AVAILABLE = "N/A"
ONLINER = "onliner"
OZBY = "ozby"
OZON = "ozon"
RUB = "RUB"
TESERA = "tesera"
TWENTYFIRSTVEK = "twentyfirstvek"
USD = "USD"
VK = "vk"
WILDBERRIES = "wb"
ZNAEMIGRAEM = "znaemigraem"
