"""
App Constants
"""
BELARUS = "Беларусь"
BGG = "bgg"
FIFTHELEMENT = "fifthelement"
KUFAR = "kufar"
NOT_AVAILABLE = "N/A"
ONLINER = "onliner"
OZBY = "ozby"
OZON = "ozon"
TESERA = "tesera"
TWENTYFIRSTVEK = "twentyfirstvek"
VK = "vk"
WILDBERRIES = "wb"
ZNAEMIGRAEM = "znaemigraem"

BYN = "BYN"
