templates:
  dir: templates
kufar:
  game_category_id: 4140
wildberries:
  game_category_id: 267
ozon:
  game_category_id: nastolnye-igry-13507
ozby:
  game_category_id: 1103640
fifthelement:
  game_category_id: 505,507
  search_app_id: 11432
vk:
  group_id: 183209921
  group_name: baraholkanastolokrb
  api_version: 5.131
  api_token: ${VK_API_TOKEN}
  limit: 50
app:
  suggested_games: Gloomhaven, Inis, Nemesis, Too Many Bones, Twilight Struggle, Mansions of Madness, Сумерки Империи, Война Кольца, Terraforming Mars, Сквозь века, Остров духов,
  Terra Mystica, Крылья, Виноделие, Root, Imperial Assault, Azul, Patchwork, Серп
exchange_rate:
  base: BYN
  target: USD
